### ISSUE TITLE
Using a custom Discord API Library

### ISSUE THREAD

**Issue by WillKenzie** [sophieproject/sophiebot#10]
There are plenty of Discord libraries out there, they all can provide diverse functionality and dynamic updates - which is great for many bots out there.

Sophie's average processing time is 2ms and this number will grow substantially as we deploy her, but one aspect is left unprepared for - the Discord API itself. We could move Sophie's entire codebase to every single datacenter that Discord's API resides in, to reduce API latency, and this would work; but what about decreasing the processing time in the API Library itself and perhaps slimming it down to reduce process time? This could trim off a few milliseconds and with the right code, it could likely perform greatly.

If we decide to do this, I can learn Typescript and fork the known Discord.ts library, slim it down to do only what we need it to do, and attach a timer to it. It may perform **much** better than before!

@faultydev what do you think? Worth the effort?

**Comment by faultydev** [comment]
dude, chill. we already achieve 2ms on regular js.

**Comment by faultydev** [comment]
2ms, we're prolly setting up shards and stuff so that wont change. chill.

**Comment by WillKenzie** [comment]
You are ignoring the fact we could trim down API Processing time - which could help achieve lower processing time.

It may be 2ms now, but once Sophie is launched it can skyrocket - we discussed this last night. Why not prepare for the issue now?

**Comment by WillKenzie** [comment]
No real interest in pursuing a custom API library at this time.
