### ISSUE TITLE
Operation Reduce Dependencies

### ISSUE THREAD

**Issue by WillKenzie** [sophieproject/sophiebot#11]
As Sophie grows, we are worried about her size eventually leading to her downfall. As of currently she has 91 total dependencies (from `npm install`) and no vulnerabilities were found.
As we all know, this can change very quickly.
In an effort to secure Sophie further and to reduce her file size (she is 12.2 MB right now!) we are going to cut down on dependencies that are not needed.

Portfinder: This can be replaced with a simple fetch() command, instead of the 24.5 KB it currently takes up, not to mention the 3 dependencies added.

DotEnv: Don't get me wrong, this is a great library, it is standard on almost every gitignore to ignore .env files. However, we write our own gitignores most of the time. This library does nothing more than provide a plaintext interface, it offers no further encryption or protection. A creds.js file can replace this library, along with a change in the gitignore.

BetterSQLite3: We love SQLite, however it may become more of a burden and we are not planning on depending on it much longer. Co-author of Sophie @faultydev has written a library called MARK that will work perfectly for storing Sophie's database in a, later to be encrypted, JSON file. 
I will write an API wrapper for this, assuming faultydev hasn't already, and we can use it as a database server for Sophie. Since this database is JSON-focused, it should also return results in JSON, which means we won't need another dependency for it. Simply use fetch. 
This will reduce Sophie by quite a bit, although it'll take some thought to bring MARK up to standards with security, hopefully including SSL and CORS, OAuth2, and more. You will see this activity in this repository as well as another.

Discord.js: It is fairly obvious that we will need some form of Discord API library, however we may look into a slimmer alternative or slim Discord.js down ourselves to reduce the overhead as well as hopefully increase the response time. This will take time, however, and we may not see good results until much later.

**Comment by WillKenzie** [comment]
DotEnv and Portfinder are removed safely, also, abandoned changes in the development branch have been relocated and will be committed shortly.

**Comment by WillKenzie** [comment]
Discord.js Alternative meets Issue #10 
We tried this over the last few days and we found that our custom library (now archived) took an average of 10ms to process information when combined with Sophie, whereas Discord.js took about 2ms.

We will not be using the custom Sophie Discord API Library upon release.

**Comment by WillKenzie** [comment]
Sophie has DevDependencies for Discord.js, which takes it from 8 dependencies to over 20. Fixing this will reduce the overall dependency count.

**Comment by WillKenzie** [comment]
Modified Discord.js meets errors... lots of errors. @faultydev may be able to do better than me in this regard.

**Comment by faultydev** [comment]
> Modified Discord.js meets errors... lots of errors. @faultydev may be able to do better than me in this regard.

We'll see.
