### ISSUE TITLE
Weird issue with bot commands.

### ISSUE THREAD

**Issue by faultydev** [sophieproject/sophiebot#9]
Whenever I send !help or !eval or anything, Sophie deletes my message...
Could be fixed with an array of allowed prefixes and words...

**Comment by WillKenzie** [comment]
Adding the array would take too much time and allow for a bypass (picture someone running `%command sned nudes` when `%command` is whitelisted.

Appears to be an issue with ALL messages, will evaluate code for potential issue.

**Comment by WillKenzie** [comment]
When point value is undefined, it returns 404.
Now, it returns 0. May break code that decides if the user exists based on userPoints() but will evaluate code again.

This issue should be resolved.
